name: Run Tests

on: [push, pull_request]

jobs:
  run:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', '2.5.x', '2.4.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: script/ci/install_deps
    - name: Run tests
      run: bundle exec rake
    - name: Test Dockerfile
      steps:
        - name: Build container
          run: docker build -t linguist .
        - name: Analyse current directory
          run: docker run --rm -v $(pwd):$(pwd) -w $(pwd) -t linguist > output
        - name: Confirm analysis
          run: |
            cat output
            grep foo output
    - name: Check Licenses
      run: script/licensed status
